/**
 * DocumentArchivist.js — FUSIONARY (v1.0)
 * ─────────────────────────────────────────────────────────────────────────────
 * Hierarchical document archive manager. Stores every artifact produced
 * by FUSIONARY under /research/<category>/<topic>/<id>/ with a manifest.json
 * that records metadata, tags, references, and patent-eligibility flags.
 *
 * Categories:
 *   - topics/         Background research notes on a specific concept
 *   - hypotheses/     Formalised hypothesis records (LLM or template)
 *   - designs/        Reactor or sub-system design proposals
 *   - simulations/    Numerical simulation reports (Lawson, MHD, neutronics)
 *   - patents/        Patent application drafts (claims + drawings + spec)
 *   - cross_refs/     Cross-reference indices that link documents together
 *   - indices/        Top-level indices (master.md, patent_queue.md, ...)
 *
 * Each document directory contains:
 *   - manifest.json   – machine-readable metadata
 *   - main.tex        – LaTeX source (when applicable)
 *   - main.pdf        – compiled PDF (when LaTeX is available)
 *   - figures/        – embedded figures
 *   - references.bib  – BibTeX bibliography
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { EventEmitter } from 'eventemitter3';
import { v4 as uuidv4 } from 'uuid';
import {
  existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, statSync,
} from 'node:fs';
import { join, dirname, basename } from 'node:path';

const CATEGORIES = Object.freeze([
  'topics',
  'hypotheses',
  'designs',
  'simulations',
  'patents',
  'cross_refs',
  'indices',
]);

const TAG_PALETTE = new Set([
  'magnetic_confinement', 'inertial_confinement', 'magneto_inertial',
  'aneutronic', 'tritium_breeding', 'HTS_magnet', 'liquid_wall',
  'PFC', 'neutronics', 'fuel_cycle', 'economics', 'safety',
  'patent_ready', 'patent_pending', 'intermediate_result', 'final_result',
  'cross_cutting', 'baseline_knowledge', 'human_directed',
]);

export class DocumentArchivist extends EventEmitter {
  constructor(opts = {}) {
    super();
    this.rootDir = opts.rootDir ?? join(process.cwd(), 'research');
    this.ensureLayout();
    this._indexCache = null;
  }

  ensureLayout() {
    if (!existsSync(this.rootDir)) mkdirSync(this.rootDir, { recursive: true });
    for (const cat of CATEGORIES) {
      const dir = join(this.rootDir, cat);
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    }
    // Master index file
    const masterIndex = join(this.rootDir, 'INDEX.md');
    if (!existsSync(masterIndex)) {
      writeFileSync(masterIndex, [
        '# FUSIONARY Research Archive — Master Index',
        '',
        '> Auto-generated by DocumentArchivist. Do not edit by hand;',
        '> run `npm run archive` to regenerate.',
        '',
        '## Categories',
        '',
        ...CATEGORIES.map(c => `- [${c}](./${c}/)`),
        '',
        '## Patent Queue',
        '',
        'See [indices/patent_queue.md](./indices/patent_queue.md) for documents',
        'flagged as patent-ready.',
        '',
      ].join('\n'));
    }
  }

  /**
   * Archive a document.
   * @param {object} doc
   * @param {string} doc.category       – One of CATEGORIES
   * @param {string} doc.title
   * @param {string} [doc.topic]        – Topic subfolder
   * @param {string} [doc.latexSource]  – TeX content
   * @param {string} [doc.markdownSource] – Markdown content (for indices)
   * @param {string[]} [doc.tags]
   * @param {string[]} [doc.references] – BibTeX keys or URLs
   * @param {object} [doc.patent]       – { eligible: bool, claims: string[] }
   * @param {object} [doc.extra]        – Arbitrary metadata
   * @returns {object} record – Manifest record with paths
   */
  archive(doc) {
    if (!CATEGORIES.includes(doc.category)) {
      throw new Error(`Invalid category: ${doc.category}. Must be one of ${CATEGORIES.join(', ')}`);
    }
    const id = doc.id ?? `doc_${uuidv4().slice(0, 8)}`;
    const topic = doc.topic ? doc.topic.replace(/[^a-zA-Z0-9_-]/g, '_') : 'general';
    const dir = join(this.rootDir, doc.category, topic, id);
    mkdirSync(dir, { recursive: true });
    mkdirSync(join(dir, 'figures'), { recursive: true });

    // Sanitise tags
    const tags = Array.isArray(doc.tags)
      ? doc.tags.filter(t => TAG_PALETTE.has(t) || t.startsWith('custom:'))
      : [];

    const manifest = {
      id,
      version: '1.0',
      title: doc.title ?? 'Untitled',
      category: doc.category,
      topic,
      tags,
      references: Array.isArray(doc.references) ? doc.references : [],
      patent: doc.patent ?? { eligible: false, claims: [] },
      createdAt: Date.now(),
      updatedAt: Date.now(),
      extra: doc.extra ?? {},
      files: {},
    };

    if (doc.latexSource) {
      const texPath = join(dir, 'main.tex');
      writeFileSync(texPath, doc.latexSource);
      manifest.files.latex = 'main.tex';
    }
    if (doc.markdownSource) {
      const mdPath = join(dir, 'main.md');
      writeFileSync(mdPath, doc.markdownSource);
      manifest.files.markdown = 'main.md';
    }
    if (doc.bibliography) {
      const bibPath = join(dir, 'references.bib');
      writeFileSync(bibPath, doc.bibliography);
      manifest.files.bibliography = 'references.bib';
    }

    writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));

    this._indexCache = null; // invalidate
    this.emit('archived', { id, dir, manifest });
    return { id, dir, manifest };
  }

  /** Recursively list all manifests in a category. */
  list(category = null) {
    const results = [];
    const cats = category ? [category] : CATEGORIES;
    for (const cat of cats) {
      const catDir = join(this.rootDir, cat);
      if (!existsSync(catDir)) continue;
      this._walkManifests(catDir, results);
    }
    return results;
  }

  _walkManifests(dir, results) {
    let entries;
    try { entries = readdirSync(dir); } catch { return; }
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      let stat;
      try { stat = statSync(fullPath); } catch { continue; }
      if (stat.isDirectory()) {
        this._walkManifests(fullPath, results);
      } else if (entry === 'manifest.json') {
        try {
          const manifest = JSON.parse(readFileSync(fullPath, 'utf8'));
          results.push({ manifest, dir: dirname(fullPath) });
        } catch (err) {
          this.emit('warning', { stage: 'list', file: fullPath, error: err.message });
        }
      }
    }
  }

  /** Find documents eligible for patent filing. */
  patentQueue() {
    return this.list().filter(r => r.manifest.patent?.eligible === true);
  }

  /** Full-text search over titles and tags. */
  search(query) {
    const q = (query ?? '').toLowerCase().trim();
    if (!q) return [];
    return this.list().filter(r => {
      const m = r.manifest;
      const haystack = `${m.title} ${m.tags.join(' ')} ${m.topic}`.toLowerCase();
      return haystack.includes(q);
    });
  }

  /** Regenerate the master INDEX.md and the patent queue. */
  rebuildIndices() {
    const all = this.list();
    const byCategory = new Map();
    for (const r of all) {
      if (!byCategory.has(r.manifest.category)) byCategory.set(r.manifest.category, []);
      byCategory.get(r.manifest.category).push(r);
    }

    // Master INDEX
    const lines = [
      '# FUSIONARY Research Archive — Master Index',
      '',
      `> Auto-generated by DocumentArchivist on ${new Date().toISOString()}`,
      `> Total documents: ${all.length}`,
      '',
      '## Categories',
      '',
      ...CATEGORIES.map(c => {
        const count = byCategory.get(c)?.length ?? 0;
        return `- [${c}](./${c}/) — ${count} document${count === 1 ? '' : 's'}`;
      }),
      '',
      '## Patent Queue',
      '',
      `See [indices/patent_queue.md](./indices/patent_queue.md) for ${this.patentQueue().length} patent-ready documents.`,
      '',
      '## Recent Documents (last 10)',
      '',
      ...all
        .sort((a, b) => b.manifest.createdAt - a.manifest.createdAt)
        .slice(0, 10)
        .map(r => `- ${new Date(r.manifest.createdAt).toISOString().slice(0,10)} — [${r.manifest.title}](./${r.manifest.category}/${r.manifest.topic}/${r.manifest.id}/)  \`${r.manifest.tags.join(', ')}\``),
      '',
    ];
    writeFileSync(join(this.rootDir, 'INDEX.md'), lines.join('\n'));

    // Patent queue
    const pq = this.patentQueue();
    const pqLines = [
      '# FUSIONARY Patent Queue',
      '',
      `> ${pq.length} document${pq.length === 1 ? '' : 's'} flagged as patent-eligible.`,
      '',
      '| Date | Title | Topic | Claims | Path |',
      '|------|-------|-------|--------|------|',
      ...pq.map(r => {
        const m = r.manifest;
        const date = new Date(m.createdAt).toISOString().slice(0, 10);
        const claims = (m.patent.claims ?? []).length;
        const path = `../${m.category}/${m.topic}/${m.id}/`;
        return `| ${date} | ${m.title} | ${m.topic} | ${claims} | [open](./${path}) |`;
      }),
      '',
    ];
    mkdirSync(join(this.rootDir, 'indices'), { recursive: true });
    writeFileSync(join(this.rootDir, 'indices', 'patent_queue.md'), pqLines.join('\n'));

    this.emit('indicesRebuilt', { total: all.length, patents: pq.length });
    return { total: all.length, patents: pq.length };
  }

  stats() {
    const all = this.list();
    const byCategory = {};
    for (const cat of CATEGORIES) byCategory[cat] = 0;
    for (const r of all) byCategory[r.manifest.category] = (byCategory[r.manifest.category] ?? 0) + 1;
    return {
      total: all.length,
      byCategory,
      patentEligible: this.patentQueue().length,
    };
  }
}

export { CATEGORIES, TAG_PALETTE };
